version: '3.8'

services:
  wordpress:
    image: wordpress:6.5.2-php8.2-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - wordpress
    volumes:
      # Only mount nginx.conf if it exists and is valid
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
